### ISSUE TITLE
TypeError: Cannot read  property 'split' of undefined

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#200]
This error happend after running `npx frontity dev`, but I wasn't able to reproduce it again.

The line where the execution fails is [this one](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/postType.ts#L39). It seems like `data.id` exists but `data.type` doesn't for some cases.

```
TypeError: Cannot read property 'split' of undefined
    at __webpack_exports__.default.str (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:73)
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:6:143)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'split' of undefined
    at __webpack_exports__.default.str (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:73)
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:6:143)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'split' of undefined
    at __webpack_exports__.default.str (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:73)
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:6:143)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by luisherranz** [comment]
Closing until we have the steps to reproduce the problem.

**Comment by warlockeg** [comment]
i tried to install Chakra UI then switched back to Mars theme on [Visit Guide](https://visit.guide) - Hint: its RTL Arabic website.

I face the exact same issue and you can see it anytime on localhost using team viewer!

Home page works fine, categories don't and posts don't ( INTERNAL SERVER ERROR )

  TypeError: Cannot read property 'split' of undefined
      at __webpack_exports__.default (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:73)
      at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/taxonomy.ts:14:400)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at eval (webpack-internal:///./node_modules/@frontity/wp-source/src/actions.ts:18:101)

**Comment by DAreRodz** [comment]
Hey @warlockeg, let's continue the conversation in the issue you opened.

**Comment by jitenit** [comment]
I am also facing **Same issue in console with mars theme** . I just setup default theme and updated my menu url

my-app.module.7518776708d6667a905f.js:51 Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at He (my-app.module.7518776708d6667a905f.js:51)
    at Object.e (my-app.module.7518776708d6667a905f.js:51)
    at e.next (<anonymous>)
    at Ge (my-app.module.7518776708d6667a905f.js:51)
    at a (my-app.module.7518776708d6667a905f.js:51)
    at my-app.module.7518776708d6667a905f.js:6
    at eu (my-app.module.7518776708d6667a905f.js:22)
    at i (my-app.module.7518776708d6667a905f.js:6)
    at t (my-app.module.7518776708d6667a905f.js:6)

**Comment by michalczaplinski** [comment]
Hey @jitenit Could you open a bug report issue with the description of the problem, following https://github.com/frontity/frontity/issues/new?template=bug_report.md. 
If you've edited the default theme please include the exact changes, thanks! 🙂

**Comment by magcrider** [comment]
I am having the same error on my 2 frontity test installations, I decided to check why and created an about-us page in both and compared it with the default Frontity website https://test.frontity.org/

I found in my installations I am getting `isFetching:true` and `isReady:False` for every WP page when checking `frontity.state.source.data`:
![image](https://user-images.githubusercontent.com/1149533/129813614-a127407e-1038-4e2c-92aa-50c0bd75ad7e.png)

testing just by changing `state.source.url` to `https://test.frontity.org/` it works perfectly:
![image](https://user-images.githubusercontent.com/1149533/129814065-daf29ddd-454b-4425-a4df-874c06343ac6.png)

I do not know if that is a light to find the problem, but not being able to load pages is difficult for the project I am working on.
