### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mburridge** [frontity/frontity#523]
**Expected behavior**

When adding a `<Head>` component the application should continue working as before and the elements defined in the <Head> component get added to the `<head>` element of the HTML.

**Observed behavior**

When a `<Head>` component is added to the project the application renders a white screen with the following in the console:

![image](https://user-images.githubusercontent.com/20643925/88279257-a6689f80-ccdb-11ea-98d1-d26859a726ef.png)

The application works normally again when the `<Head>` component is removed/commented out.

Refreshing the page in the browser results in 'Internal Server Error' being displayed in browser and the following in the terminal:

```
TypeError: Cannot read property 'add' of undefined
      at e.init (webpack-internal:///./packages/wc-sevilla-theme/node_modules/react-helmet-async/lib/index.module.js:14:9183)
      at e.render (webpack-internal:///./packages/wc-sevilla-theme/node_modules/react-helmet-async/lib/index.module.js:14:9256)
      at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:402:631)
      at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:396:122)
      at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:1199)
      at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:55)
      at renderToString (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:470:116)
      at eval (webpack-internal:///./node_modules/@frontity/core/src/server/index.tsx:45:243)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at eval (webpack-internal:///./node_modules/koa-mount/index.js:16:290)
```

**Steps involved to reproduce the problem**

This error occurs in one individual project. It does not occur in other projects in the same dev environment. It does not occur in other projects accessing the same WP API. It continues to occur in the affected project even if you change the WP API to a different one.

Others have experienced similar issues:
https://community.frontity.org/t/head-tags-internal-server-error/2474
https://community.frontity.org/t/head-giving-error-cannot-read-property-add-of-undefined/2420

**Repo**
https://github.com/mburridge/wc-sevilla-frontity-project

**Info about your system**

```
## System:
 - OS: macOS 10.15.5
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 668.77 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
## Browsers:
 - Chrome: 84.0.4147.89
 - Firefox: 78.0.2
 - Safari: 13.1.1
## npmPackages:
 - @frontity/core: ^1.5.1 => 1.5.1 
 - @frontity/head-tags: ^1.0.2 => 1.0.2 
 - @frontity/html2react: ^1.3.1 => 1.3.1 
 - @frontity/mars-theme: ./packages/mars-theme => 1.4.0 
 - @frontity/tiny-router: ^1.1.1 => 1.1.1 
 - @frontity/wp-source: ^1.6.2 => 1.6.2 
 - frontity: ^1.5.2 => 1.5.2 
 - wc-sevilla-theme: file:packages/wc-sevilla-theme => 1.0.0 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found
```

**Comment by SantosGuillamot** [comment]
In case it helps: I've run a quick test and I made the repo work with the `<Head />` component after deleting `node_modules` and the `package-lock.json` of the project and the local packages, and running `npm install`, as explained in [the docs](https://docs.frontity.org/guides/keep-frontity-updated#troubleshooting).

Apart from that, I think we should provide a more descriptive name for the bug.

**Comment by mburridge** [comment]
Thanks @SantosGuillamot, I'd done that in the root of the project but not for the local packages. It's working now. 🙌

I'll suggest this to the people in the forum experiencing similar issues.

**Comment by Jolle775** [comment]
same issue here, deleted all node_modules, package-lock.json 

`  TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at getKeys (webpack-internal:///./node_modules/deepmerge/dist/umd.js:2:1009)
      at mergeObject (webpack-internal:///./node_modules/deepmerge/dist/umd.js:2:1282)
      at deepmerge (webpack-internal:///./node_modules/deepmerge/dist/umd.js:2:2056)
      at eval (webpack-internal:///./node_modules/@frontity/core/src/utils/merge-packages.ts:8:484)
      at Array.forEach (<anonymous>)
      at __webpack_exports__.default (webpack-internal:///./node_modules/@frontity/core/src/utils/merge-packages.ts:8:226)
      at __webpack_exports__.default (webpack-internal:///./node_modules/@frontity/core/src/server/store.ts:5:271)
      at eval (webpack-internal:///./node_modules/@frontity/core/src/server/index.tsx:47:68)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

**Comment by mburridge** [comment]
Looks like that's the fix: https://community.frontity.org/t/head-tags-internal-server-error/2474/7

**Comment by SantosGuillamot** [comment]
Great! Then I'm going to close this issue for now.
