### ISSUE TITLE
 TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Sanjeevsetu** [frontity/frontity#807]
TypeError: Cannot read property 'name' of undefined
      at state (webpack-internal:///./node_modules/@frontity/core/src/server/utils/initial-state.ts:15:395)
      at store (webpack-internal:///./node_modules/@frontity/core/src/server/store.ts:14:124)
      at eval (webpack-internal:///./node_modules/@frontity/core/src/server/middlewares/settings-and-store.ts:21:83)
      at eval (webpack-internal:///./node_modules/koa-mount/index.js:16:290)

**Comment by luisherranz** [comment]
Hi @Sanjeevsetu, please provide a CodeSandbox and a concise list of steps that we need to do to reproduce the bug. Feel free to reopen this issue once that is added 🙂
