### ISSUE TITLE
not working frontity (I like to run Frontity but I can not help please)

### ISSUE THREAD

**Issue by vb147** [frontity/frontity#838]
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
  1. You might have mismatching versions of React and the renderer (such as React DOM)
  2. You might be breaking the Rules of Hooks
  3. You might have more than one copy of React in the same app
  See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
      at resolveDispatcher (webpack-internal:///./node_modules/react/cjs/react.development.js?5187:310:1206)
      at useState (webpack-internal:///./node_modules/react/cjs/react.development.js?5187:313:485)
      at Theme (webpack-internal:///./node_modules/@frontity/connect/src/connect.js?6871:36:72)
      at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:443:2321)
      at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:442:122)
      at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:484:1233)
      at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:484:55)
      at renderToString (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:528:132)
      at render (webpack-internal:///./node_modules/@frontity/core/src/server/middlewares/capabilities/render-method.tsx:12:318)
      at serverSideRendering (webpack-internal:///./node_modules/@frontity/core/src/server/middlewares/server-side-rendering.ts:33:15)

**Comment by luisherranz** [comment]
Please, follow the bug template and provide a [codesandbox/stackblitz](https://github.com/frontity/frontity-template) that reproduces the bug.

**Comment by vb147** [comment]
Why does this error occur in my system? Do React Versions Overlap? Do I have to define a alias for React in Web Pack?
