### ISSUE TITLE
Why does this error occur in my system? Do React Versions Overlap? Do I have to define a alias for React in Web Pack?

### ISSUE THREAD

**Issue by vb147** [frontity/frontity#839]
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

You might have mismatching versions of React and the renderer (such as React DOM)
You might be breaking the Rules of Hooks
You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
at resolveDispatcher (webpack-internal:///./node_modules/react/cjs/react.development.js?5187:310:1206)
at useState (webpack-internal:///./node_modules/react/cjs/react.development.js?5187:313:485)
at Theme (webpack-internal:///./node_modules/@frontity/connect/src/connect.js?6871:36:72)
at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:443:2321)
at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:442:122)
at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:484:1233)
at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:484:55)
at renderToString (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:528:132)
at render (webpack-internal:///./node_modules/@frontity/core/src/server/middlewares/capabilities/render-method.tsx:12:318)
at serverSideRendering (webpack-internal:///./node_modules/@frontity/core/src/server/middlewares/server-side-rendering.ts:33:15)

**Comment by luisherranz** [comment]
Hi @vb147. Again, if you think that there is a bug in Frontity please follow the BUG TEMPLATE that appears when you click on the `New Issue` button. Thanks 🙂
