### ISSUE TITLE
Getting error while running " npx frontity dev"

### ISSUE THREAD

**Issue by janakkaneriya007** [frontity/frontity#89]
Hi Team,

I have tried the framework and it's working fine.

But I am facing some issue while running the command " npx frontity dev"

detailed question.

When I setup the demo as stated in get started guide and run the command " npx frontity dev" it's working fine but when I stop the server and try to run the command " npx frontity dev" again it gives me below error:
Error: listen EADDRINUSE :::3000
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at Server.listen (net.js:1492:7)
at start (/home/md0122-janak/my-app/node_modules/@frontity/core/dist/scripts/utils/create-app.js:19:20)
at compiler.compilers.(anonymous function).hooks.done.tapAsync (/home/md0122-janak/my-app/node_modules/@frontity/core/dist/scripts/utils/create-app.js:28:13)
at _next0 (eval at create (/home/md0122-janak/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), :26:1)
at _err0 (eval at create (/home/md0122-janak/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), :41:1)
at Immediate. (/home/md0122-janak/my-app/node_modules/webpack-bundle-analyzer/lib/BundleAnalyzerPlugin.js:77:13)

So, next if I want to work with the project I have to reboot my system and then I can work.

For the information, I am using the ubuntu system.

Let, me know if you need more details on this.

**Comment by luisherranz** [comment]
Hey @janakkaneriya007 thanks for joining Frontity :)

@orballo has already answered you in the community forum so I'm going to close this issue.

Please follow the conversation there if you still have problems:
https://community.frontity.org/t/getting-error-while-running-npx-frontity-dev/209
