### ISSUE TITLE
frontity Warning: Closing file descriptor 3 on garbage collection

### ISSUE THREAD

**Issue by SquerlInMyPants** [frontity/frontity#910]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Create a development server.

**Observed behavior**

![image](https://user-images.githubusercontent.com/79985119/157670461-cf3bee6b-6cc8-440f-be1b-1ac34f9f8cf1.png)

**Steps involved to reproduce the problem**

Start a development server using the follow **npm** command in the terminal:
`npm run dev`

**Info about your system**

## System:
 - OS: Windows 10 10.0.19042
 - CPU: (2) x64 AMD E1-2500 APU with Radeon(TM) HD Graphics
 - Memory: 387.91 MB / 3.43 GB
## Binaries:
 - Node: 17.2.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Chrome: 99.0.4844.51
 - Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.30)
 - Internet Explorer: 11.0.19041.1202
## npmPackages:
 - @frontity/core: ^1.15.0 => 1.15.0
 - @frontity/html2react: ^1.7.0 => 1.7.0
 - @frontity/mars-theme: ./packages/mars-theme => 1.6.2
 - @frontity/tiny-router: ^1.4.4 => 1.4.4
 - @frontity/wp-source: ^1.11.7 => 1.11.7
 - frontity: ^1.17.2 => 1.17.2
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

I do not know single solution for this predicament.

**Comment by richhauck** [comment]
I was getting this same error using Node v17. My workaround was to use [Node Version Manager](https://github.com/nvm-sh/nvm) to revert to v16.8.

**Comment by myspeak852** [comment]
When I build the code then shows an error, some help is required.
Building es5 bundle
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/workspace/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/workspace/node_modules/babel-plugin-lodash/lib/index.js:102:44)
Error: list.es5.96f64d8107e8a27ab60b.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at /workspace/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/workspace/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/workspace/node_modules/tapable/lib/Hook.js:154:20)
    at /workspace/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/workspace/node_modules/tapable/lib/Hook.js:154:20)
    at /workspace/node_modules/webpack/lib/Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create
-----------------------------------------------------------------------
Thank you
